name: Build Installers

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]
        include:
          - platform: windows-latest
            artifact_path: "src-tauri/target/release/bundle/msi/*.msi"
          # - platform: ubuntu-latest
          #   artifact_path: "src-tauri/target/release/bundle/deb/*.deb"

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      # - name: Install Linux Dependencies
      #   if: matrix.platform == 'ubuntu-20.04'
      #   run: |
      #     sudo apt update
      #     sudo apt install libwebkit2gtk-4.1-dev \
      #       build-essential \
      #       curl \
      #       wget \
      #       file \
      #       libxdo-dev \
      #       libssl-dev \
      #       libayatana-appindicator3-dev \
      #       librsvg2-dev

      - name: Install dependencies on server submodule
        run: |
          cd server
          npm ci
          cd ..

      - name: Install dependencies for tauri
        run: |
          npm ci

      - name: Build server executables
        run: |
          npm run build:server

      - name: Move server executable
        run: |
          npm run build:server:bin

      - name: Build tauri release version
        run: |
          npm run tauri build --release

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.artifact_path }}
